# Generated by Django 4.0.4 on 2022-06-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='score',
            field=models.SmallIntegerField(choices=[(1, '0 分'), (2, '20 分'), (3, '40 分'), (4, '60 分'), (5, '80 分'), (6, '100 分')], default=5, verbose_name='满意度评分'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (2, '支付宝')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '已完成'), (5, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
