# Generated by Django 4.0.4 on 2022-05-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_user_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
