# 图形验证码有效期 单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300
# 短信验证码有效期 单位：秒
SMS_CODE_REDIS_EXPIRES = 300
# 短信模板
SEND_SMS_TEMPLATE_ID = 1
# 60s 内是否重复发送标记
SEND_SMS_CODE_INTERVAL = 60
# Cookie 过期时间设置
CARTS_COOKIE_EXPIRES = 60 * 1000 * 15